# This is a basic workflow to help you get started with Actions

name: bumper

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/5 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

jobs:
  # This workflow contains a single job called "build"
  bump-issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs sh command to echo issues
      - name: Echo issues that might be related to serverless
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./issue_listener.sh
